from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path

CANARY_DIR = ".agent-tripwire"
CANARY_FILE = "canaries.env"
CANARIES = {
    "AGENTTRIPWIRE_AWS_ACCESS_KEY_ID": "AKIAFAKEAGENTTRIPWIRE0000",
    "AGENTTRIPWIRE_GITHUB_TOKEN": "ghp_fake_agent_tripwire_token_do_not_use",
    "AGENTTRIPWIRE_SSH_KEY_ID": "tripwire-demo-key-0000",
}


@dataclass(frozen=True)
class Finding:
    path: str
    name: str
    line: int


def plant(root: Path) -> Path:
    target_dir = root / CANARY_DIR
    target_dir.mkdir(exist_ok=True)
    target = target_dir / CANARY_FILE
    lines = ["# Fake canaries generated by AgentTripwire. Do not use as credentials."]
    lines += [f"{key}={value}" for key, value in CANARIES.items()]
    target.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return target


def scan(root: Path) -> list[Finding]:
    findings: list[Finding] = []
    values = set(CANARIES.values())
    for path in root.rglob("*"):
        if not path.is_file() or ".git" in path.parts:
            continue
        try:
            for number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
                for name, value in CANARIES.items():
                    if value in line and path.name != CANARY_FILE:
                        findings.append(Finding(str(path), name, number))
        except UnicodeDecodeError:
            continue
    return findings


def demo(root: Path) -> list[Finding]:
    plant(root)
    log = root / CANARY_DIR / "demo-agent.log"
    log.write_text(f"agent read token: {CANARIES['AGENTTRIPWIRE_GITHUB_TOKEN']}\n", encoding="utf-8")
    return scan(root)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Plant and detect fake canary secrets.")
    sub = parser.add_subparsers(dest="cmd", required=True)
    sub.add_parser("plant")
    scan_parser = sub.add_parser("scan")
    scan_parser.add_argument("path", nargs="?", default=".")
    sub.add_parser("demo")
    args = parser.parse_args(argv)

    root = Path.cwd()
    if args.cmd == "plant":
        print(f"planted {plant(root)}")
        return 0
    if args.cmd == "scan":
        findings = scan(Path(args.path))
    else:
        findings = demo(root)

    print(json.dumps([finding.__dict__ for finding in findings], indent=2))
    return 1 if findings else 0


if __name__ == "__main__":
    raise SystemExit(main())
